# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 297ae3ea4ad05f0c81c6f006fba3c86b76b5336c88cb11166e99c92db40ef19af66b40c2ec4e45e3e3bffe084e4dde2a65d70b9cac1754fc94b05c83efa09f5b

test:
  secret_key_base: 05bd787667e52893174b0bc1969e4c53b782a67ceb3dbe2a207e87d1de15c7c26bd1488e216fb637532dcf9b83e80ad31ef6f7b6ff4d16ed55b963bda0e09776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
